version: "3.5"

services:
    base:
        build:
            dockerfile: Dockerfile
            context: ./base
        image: ollin18/base:0.1
        container_name: base
    neo4j:
        build:
            dockerfile: Dockerfile
            context: ./neo4j
        image: ollin18/planea:0.1
        container_name: planea_neo4j
        depends_on:
            - ingest
        environment:
            - NEO4J_AUTH=none
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - ../data/nodes/list:/nodes/list
            - ../data/edges/list:/edges/list
            - ../data/nodes/headers:/nodes/headers
            - ../data/edges/headers:/edges/headers
    postgres:
        image: postgres:9.6
        depends_on:
            - ingest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=planea
            - POSTGRES_PASSWORD=planea
            - POSTGRES_DB=planea
        logging:
            options:
                max-size: 20m
                max-file: "5"
        volumes:
            - ../data/:/var/lib/postgresql/data
    ingest:
        build:
            dockerfile: Dockerfile
            context: ./ingest
        image: ingest
        container_name: ingester
        depends_on:
            - base
        volumes:
            - ../data:/data
            - ../src:/src
        command: ["src/exe.sh"]

volumes:
    data:
    datasc:
    nodes:
    edges:
