version: "3.5"

services:
    base:
        build:
            dockerfile: Dockerfile
            context: ./base
        image: ollin18/base:0.1
        container_name: base
    # neo4j:
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./neo4j
    #     image: ollin18/neoplanea:0.1
    #     container_name: neoplanea
    #     depends_on:
    #         - base
    #     environment:
    #         - NEO4J_AUTH=none
    #     ports:
    #         - "7474:7474"
    #         - "7687:7687"
    #     volumes:
    #         - ../data/nodes/list:/nodes/list
    #         - ../data/edges/list:/edges/list
    #         - ../data/nodes/headers:/nodes/headers
    #         - ../data/edges/headers:/edges/headers
    postgres:
        image: "postgres:11"
        container_name: planeadb
        environment:
            - POSTGRES_USER=planea
            - POSTGRES_PASSWORD=planea
            - POSTGRES_DB=planea
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ../data/sql:/var/lib/postgresql/data
    ingest:
        build:
            dockerfile: Dockerfile
            context: ./ingest
        image: ingest
        container_name: ingester
        depends_on:
            - base
        volumes:
            - ../data:/data
            - ../src:/src
        # command: ["src/exe.sh"]

volumes:
    my_dbdata:
    data:
    datasc:
    # nodes:
    # edges:
